spring.application.name=api-gateway
server.port=8080

# Service Registry
gateway.services.transaction-service=http://localhost:8081
gateway.services.fraud-detection-service=http://localhost:8082
gateway.services.notification-service=http://localhost:8083
gateway.services.account-service=http://localhost:8084
